"""initial

Revision ID: 78a8ce692e38
Revises: 
Create Date: 2025-08-27 02:01:34.871203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a8ce692e38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shorters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('shorted_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_shorter_original_url', 'url_shorters', ['original_url'], unique=False)
    op.create_index(op.f('ix_url_shorters_original_url'), 'url_shorters', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shorters_original_url'), table_name='url_shorters')
    op.drop_index('ix_url_shorter_original_url', table_name='url_shorters')
    op.drop_table('url_shorters')
    # ### end Alembic commands ###
